apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.nginx.yml convert -o ./manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.nginx.yml convert -o ./manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 443
              protocol: TCP
      restartPolicy: Always
