apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.auth.yml convert -o ./manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: metro-alarm-server-auth
  name: metro-alarm-server-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metro-alarm-server-auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.auth.yml convert -o ./manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: metro-alarm-server-auth
    spec:
      containers:
        - args:
            - /app/scripts/app.sh
          env:
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              valueFrom:
                configMapKeyRef:
                  key: ACCESS_TOKEN_EXPIRE_MINUTES
                  name: metro_alarm_server_auth-env
            - name: ALGORITHM
              valueFrom:
                configMapKeyRef:
                  key: ALGORITHM
                  name: metro_alarm_server_auth-env
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: metro_alarm_server_auth-env
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: metro_alarm_server_auth-env
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  key: DB_PASS
                  name: metro_alarm_server_auth-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: metro_alarm_server_auth-env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: metro_alarm_server_auth-env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: metro_alarm_server_auth-env
            - name: DOCS_URL
              valueFrom:
                configMapKeyRef:
                  key: DOCS_URL
                  name: metro_alarm_server_auth-env
            - name: HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  key: HTTP_HOST
                  name: metro_alarm_server_auth-env
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: HTTP_PORT
                  name: metro_alarm_server_auth-env
            - name: LOGGING_PATH
              valueFrom:
                configMapKeyRef:
                  key: LOGGING_PATH
                  name: metro_alarm_server_auth-env
            - name: OPENAPI_URL
              valueFrom:
                configMapKeyRef:
                  key: OPENAPI_URL
                  name: metro_alarm_server_auth-env
            - name: PRIVATE_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_KEY_PATH
                  name: metro_alarm_server_auth-env
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  key: PROJECT_NAME
                  name: metro_alarm_server_auth-env
            - name: PUBLIC_KEY_PATH
              valueFrom:
                configMapKeyRef:
                  key: PUBLIC_KEY_PATH
                  name: metro_alarm_server_auth-env
            - name: REFRESH_TOKEN_EXPIRE_DAYS
              valueFrom:
                configMapKeyRef:
                  key: REFRESH_TOKEN_EXPIRE_DAYS
                  name: metro_alarm_server_auth-env
            - name: SECRET_INSIDE_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_INSIDE_KEY
                  name: metro_alarm_server_auth-env
          image: metro-alarm-server-auth
          name: metro-alarm-server-auth
          volumeMounts:
            - mountPath: /app/alembic/versions
              name: metro-alarm-server-auth-cm0
            - mountPath: /app/logs
              name: metro-alarm-server-auth-claim1
      restartPolicy: Always
      volumes:
        - configMap:
            name: metro-alarm-server-auth-cm0
          name: metro-alarm-server-auth-cm0
        - name: metro-alarm-server-auth-claim1
          persistentVolumeClaim:
            claimName: metro-alarm-server-auth-claim1
