apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.auth.yml convert -o ./manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: postgres-auth
  name: postgres-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.auth.yml convert -o ./manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: postgres-auth
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres_auth-database-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres_auth-database-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres_auth-database-env
          image: postgres:16.1-alpine3.19
          livenessProbe:
            exec:
              command:
                - pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: postgres-auth
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-auth-claim0
            - mountPath: /etc/postgresql/postgresql.conf
              name: postgres-auth-cm1
              subPath: postgresql.conf
      restartPolicy: Always
      volumes:
        - name: postgres-auth-claim0
          persistentVolumeClaim:
            claimName: postgres-auth-claim0
        - configMap:
            items:
              - key: postgresql.conf
                path: postgresql.conf
            name: postgres-auth-cm1
          name: postgres-auth-cm1
