version: '3.9'

services:
  proxy:
    depends_on:
      - metro_alarm_server_map
    build:
      dockerfile: Dockerfile
      context: ../nginx
    ports:
      - "443:443"

  metro_alarm_server_map:
    env_file:
      - ../.env/.env
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    command: ["/app/scripts/app.sh"]
    volumes:
      - ../alembic/versions:/app/alembic/versions
      - ../logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres_map:
        condition: service_healthy

  postgres_map:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../.env/.database.env
    volumes:
      - /var/lib/metro_alarm_server_auth_db:/var/lib/postgresql/data
      - ../postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"