version: '3.9'

services:
  metro_alarm_server_map:
    env_file:
      - ../map/.env/.env
    build:
      dockerfile: ../map/docker/Dockerfile
      context: ../map/
    command: ["/app/scripts/app.sh"]
    volumes:
      - ../map/alembic/versions:/app/alembic/versions
      - ../map/maps:/app/maps
      - ../map/logs:/app/logs
    depends_on:
      postgres_map:
        condition: service_healthy
    networks:
      - msa


  postgres_map:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ../map/.env/.database.env
    volumes:
      - ../map/postgres/db:/var/lib/postgresql/data
      - ../map/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - msa


networks:
  msa:
    driver: bridge
    external: true
