version: '3.9'

services:
  nginx:
    build:
      dockerfile: ../nginx/Dockerfile
      context: ../nginx/
    ports:
      - "443:443"
    networks:
      - msa

networks:
  msa:
    driver: bridge
    external: true