apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: metro-alarm-server-map-claim2
  name: metro-alarm-server-map-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
