apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.map.yml convert -o ./manifests/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: metro-alarm-server-map
  name: metro-alarm-server-map
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metro-alarm-server-map
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\dima-\utils\kompose.exe -f .\docker-compose\docker-compose.map.yml convert -o ./manifests/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: metro-alarm-server-map
    spec:
      containers:
        - args:
            - /app/scripts/app.sh
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: metro_alarm_server_map-env
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: metro_alarm_server_map-env
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  key: DB_PASS
                  name: metro_alarm_server_map-env
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: metro_alarm_server_map-env
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USER
                  name: metro_alarm_server_map-env
            - name: DEBUG
              valueFrom:
                configMapKeyRef:
                  key: DEBUG
                  name: metro_alarm_server_map-env
            - name: DOCS_URL
              valueFrom:
                configMapKeyRef:
                  key: DOCS_URL
                  name: metro_alarm_server_map-env
            - name: FIND_USER_EXISTS_URL
              valueFrom:
                configMapKeyRef:
                  key: FIND_USER_EXISTS_URL
                  name: metro_alarm_server_map-env
            - name: HTTP_HOST
              valueFrom:
                configMapKeyRef:
                  key: HTTP_HOST
                  name: metro_alarm_server_map-env
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: HTTP_PORT
                  name: metro_alarm_server_map-env
            - name: LOGGING_PATH
              valueFrom:
                configMapKeyRef:
                  key: LOGGING_PATH
                  name: metro_alarm_server_map-env
            - name: MAP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: MAP_VERSION
                  name: metro_alarm_server_map-env
            - name: MSC_MAP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: MSC_MAP_VERSION
                  name: metro_alarm_server_map-env
            - name: OPENAPI_URL
              valueFrom:
                configMapKeyRef:
                  key: OPENAPI_URL
                  name: metro_alarm_server_map-env
            - name: PROJECT_NAME
              valueFrom:
                configMapKeyRef:
                  key: PROJECT_NAME
                  name: metro_alarm_server_map-env
            - name: SECRET_INSIDE_KEY
              valueFrom:
                configMapKeyRef:
                  key: SECRET_INSIDE_KEY
                  name: metro_alarm_server_map-env
            - name: SPB_MAP_VERSION
              valueFrom:
                configMapKeyRef:
                  key: SPB_MAP_VERSION
                  name: metro_alarm_server_map-env
          image: metro-alarm-server-map
          name: metro-alarm-server-map
          volumeMounts:
            - mountPath: /app/alembic/versions
              name: metro-alarm-server-map-cm0
            - mountPath: /app/maps
              name: metro-alarm-server-map-claim1
            - mountPath: /app/logs
              name: metro-alarm-server-map-claim2
      restartPolicy: Always
      volumes:
        - configMap:
            name: metro-alarm-server-map-cm0
          name: metro-alarm-server-map-cm0
        - name: metro-alarm-server-map-claim1
          persistentVolumeClaim:
            claimName: metro-alarm-server-map-claim1
        - name: metro-alarm-server-map-claim2
          persistentVolumeClaim:
            claimName: metro-alarm-server-map-claim2
